# Generated by Django 3.2.5 on 2022-12-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('calorias', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
            ],
        ),
    ]
