# Generated by Django 3.2.5 on 2022-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelElemento',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('calorias', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='elemento',
            name='ID',
            field=models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
