# Generated by Django 3.2.5 on 2022-12-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0004_auto_20221231_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='gain',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selelemento',
            name='gain',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elemento',
            name='ID',
            field=models.PositiveSmallIntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='selelemento',
            name='ID',
            field=models.PositiveSmallIntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
