# Generated by Django 3.2.5 on 2022-12-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0005_auto_20221231_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='ID',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='gain',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='selelemento',
            name='ID',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selelemento',
            name='gain',
            field=models.FloatField(default='0'),
        ),
    ]
