# Generated by Django 3.2.5 on 2022-12-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0006_auto_20221231_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={'ordering': ['gain']},
        ),
    ]
