# Generated by Django 3.2.5 on 2022-12-31 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0007_alter_elemento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={'ordering': ['-gain']},
        ),
    ]
