# Generated by Django 3.2.5 on 2023-01-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0008_alter_elemento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='req',
            fields=[
                ('ID', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('reqcalorias', models.PositiveIntegerField(editable=False)),
                ('reqpeso', models.PositiveIntegerField(editable=False)),
            ],
        ),
    ]
