# Generated by Django 3.2.5 on 2023-01-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0009_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='ID',
        ),
        migrations.AddField(
            model_name='req',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
