# Generated by Django 3.2.5 on 2023-01-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Excursion', '0010_auto_20230101_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={},
        ),
    ]
